---
title: "Geospatial Data Science in R"
---

This course offers an in-depth exploration of geospatial data science using R, designed for researchers and practitioners seeking to enhance their analytical capabilities in spatial data. Participants will gain practical experience with R's latest spatial data technologies, integrating theory with hands-on applications. By the end of the course, participants will be equipped to apply geospatial data science techniques to real-world problems, leveraging the full power of R's spatial tools.

::: {.callout-note icon=false}

## <i class="bi bi-calendar-event"></i> When, <i class="bi bi-building"></i> Where

20-23 January 2025, 9-14 h
<span style="float:right">
[Add to Calendar](https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20250120T080000Z%2F20250123T130000Z&details=This%20course%20offers%20an%20in-depth%20exploration%20of%20geospatial%20data%20science%20using%20R%2C%20designed%20for%20researchers%20and%20practitioners%20seeking%20to%20enhance%20their%20analytical%20capabilities%20in%20spatial%20data.%20Participants%20will%20gain%20practical%20experience%20with%20R%27s%20latest%20spatial%20data%20technologies%2C%20integrating%20theory%20with%20hands-on%20applications.%20By%20the%20end%20of%20the%20course%2C%20participants%20will%20be%20equipped%20to%20apply%20geospatial%20data%20science%20techniques%20to%20real-world%20problems%2C%20leveraging%20the%20full%20power%20of%20R%27s%20spatial%20tools.&location=Campus%20de%20Getafe%2C%20Campomanes%20building%2C%20room%2010.0.30&text=Geospatial%20Data%20Science%20Course)
</span><br>
Campus de Getafe, Campomanes building, room 10.0.30
<span style="float:right">
[Location](https://www.google.com/maps/place/Edificio+Campomanes,+C.+Madrid,+126,+28903+Getafe,+Madrid/@40.3141077,-3.7266714,18z/data=!3m1!4b1!4m6!3m5!1s0xd4220bede215627:0x36d4c698be21cb0c!8m2!3d40.3141077!4d-3.725915!16s%2Fg%2F11_pvch89?entry=ttu&g_ep=EgoyMDI0MTEyNC4xIKXMDSoJLDEwMjExMjM0SAFQAw%3D%3D)
</span>

:::

::: {.callout-important}

## Pre-requisites

- Basic knowledge of statistical modelling with R.
- Participants should bring their own laptops with **R and RStudio installed**.
- Some **package dependencies** are heavy, so it is recommended to install them
  beforehand as follows:
  ```{r, eval=FALSE}
  install.packages(c("sf", "stars", "terra", "s2", "gstat", "spatstat", "spdep", "spatialreg", "mgcv"))
  install.packages("starsdata", repos = "https://cran.uni-muenster.de/pebesma", type = "source")
  install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")
  ```
- **R-INLA** is required too. For OS-specific installation instructions,
  see [this link](https://www.r-inla.org/download-install)
- If time permits, the instructor suggests reading the following chapters from
  [Spatial Data Science](https://r-spatial.org/book/):<br>3-7, 10-12, 14-16

:::

## Instructor

Dr. **Edzer Pebesma** is Professor of Geoinformatics at University of Münster, Germany.
His research interests include the computational and statistical modelling of spatio-temporal phenomena at the geographical scale.
